// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCo1du249AQLKxk03K5wK_8uvmlsSCh6s',
    appId: '1:329813726694:web:c3461cf80060228530b227',
    messagingSenderId: '329813726694',
    projectId: 'soulfulhaven-ecommerce',
    authDomain: 'soulfulhaven-ecommerce.firebaseapp.com',
    storageBucket: 'soulfulhaven-ecommerce.firebasestorage.app',
    measurementId: 'G-Y4GD4FGV9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPSi0ca_tVhQwHy5C7HPuJOlWZ6yKpMc',
    appId: '1:329813726694:android:9ac71073e91209fe30b227',
    messagingSenderId: '329813726694',
    projectId: 'soulfulhaven-ecommerce',
    storageBucket: 'soulfulhaven-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CZ5gEHfki3UYHhcOoTV8bougwcX-NhE',
    appId: '1:329813726694:ios:095bf289ef25c0e230b227',
    messagingSenderId: '329813726694',
    projectId: 'soulfulhaven-ecommerce',
    storageBucket: 'soulfulhaven-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.projectone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2CZ5gEHfki3UYHhcOoTV8bougwcX-NhE',
    appId: '1:329813726694:ios:095bf289ef25c0e230b227',
    messagingSenderId: '329813726694',
    projectId: 'soulfulhaven-ecommerce',
    storageBucket: 'soulfulhaven-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.projectone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCo1du249AQLKxk03K5wK_8uvmlsSCh6s',
    appId: '1:329813726694:web:fc9d3eaea0095f7e30b227',
    messagingSenderId: '329813726694',
    projectId: 'soulfulhaven-ecommerce',
    authDomain: 'soulfulhaven-ecommerce.firebaseapp.com',
    storageBucket: 'soulfulhaven-ecommerce.firebasestorage.app',
    measurementId: 'G-NYK045GLBB',
  );
}
